alias dsize="docker history --human --format '{{.CreatedBy}}: {{.Size}}' $*"
alias dst="docker stop $*"
alias drc="docker rm $*"
alias dri="docker rmi $*"
alias ds="docker system df"
alias dsv="docker system df -v"
alias dil="docker images -a"
alias dp="docker ps -a"
alias de="docker run -it $*"

