apiVersion: ENC[AES256_GCM,data:MT8=,iv:qw3tsgRnsjjA53IjD9VXezYLpcxW1PsXvqWfXkKEiRs=,tag:kYBT9XZKr2ktHf86V+abDQ==,type:str]
kind: ENC[AES256_GCM,data:bs5NVGOS,iv:2ZoXePRxZwPDsS0vStJxBeqDHBEV3RhEqAy+jbjzU4c=,tag:oZs9v+EPd58YCTDJpxCQAA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FtceqhMOHdk0ZPk=,iv:W1Wzy9F5GOu/cnTfPSeuTgMtTeVv9i5Vc8boDQo5EnI=,tag:sxNIuGSUpqSWeCs7E0wgig==,type:str]
type: ENC[AES256_GCM,data:iCS0zAhO,iv:ZH+bMstrZrnNj/eD3Jh+lKpy5eOdnNhVScEdJoGoIHg=,tag:gjcoqgctIatrE7xkutxO5g==,type:str]
stringData:
    AZP_TOKEN: ENC[AES256_GCM,data:HAcWt65nJ2J8caXQe+wIvYQzkUXIFB7bYW1eO4smdhrmg49gpAWXotdjp6b5iyoYmdP/VCRBG3jfS+wWdEn9tmm+eGRWNENlDQiW31zFLkgy1c+k,iv:T8ztlGdcwbLOnp419hm7N+QrI5nU2BoNPByKARN0uKQ=,tag:9exJw7ukBWBKYByAAZW3Zw==,type:str]
    AZP_URL: ENC[AES256_GCM,data:p/hGns1ZkWSk/lgsW2x9GmoaOnnEHExItHctRdQ=,iv:59oPW/J+r3wzrTvcxwaWibWqBdtnU8uy0a5TNA0acXA=,tag:2So+c+iagqRqU3OqKk8rLw==,type:str]
sops:
    lastmodified: "2025-08-15T16:08:30Z"
    mac: ENC[AES256_GCM,data:RCknVOtxmeM6X4HsPKQBWRC1GAw7sHjRiNMBGyDjJF/8iBYuAnU1gDaSmVrA0XTfLiXMiExSNsuTfT25WTCQxNA8cWmDDqerJMhEX8xt/sMaENmiC4TRi1QlQGpRVZJjyWnePIrhIUKrhBJOj+2MXuU+lTg8HWTQD60mGQT2uY4=,iv:xs5y4nxWV3m/Y9wkAWZn44b8XwuIFUtE3NPg0MVoJF8=,tag:AKG/+LEOdx1qa7pAyCNQ3Q==,type:str]
    pgp:
        - created_at: "2025-08-15T16:08:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DvU7RnG+LjsASAQdArwfnYLtn7rJyu2c8U1hDvrHcFiD/JF7vNVqE/fD4iAMw
            veTwYaFp1o66E38G87HoQd6ZD4hqc5izPee1XJCdfPMw/8NtY+i6/pS5D06Y9wiC
            1GgBCQIQJSEVWo/2RsR/xV3D8e3sAWNRQ8zit+Lcjh7Xx1a1A5ocgMzfej1Bw58m
            oLg7REZXYiIYjqwNsaYV9EKEZiXw/xdElYpFOkJjzTUc+e67Hf/3DXclArANjDE9
            W6ves7yT5QdLBg==
            =qlT2
            -----END PGP MESSAGE-----
          fp: C3F9DF295E796FFC
    unencrypted_suffix: _unencrypted
    version: 3.10.2
